# Generated by Django 6.0 on 2025-12-16 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration value')),
                ('duration_type', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=10)),
                ('features', models.JSONField(default=list, help_text='List of plan features')),
                ('classes_per_week', models.IntegerField(blank=True, help_text='Null means unlimited', null=True)),
                ('personal_training_sessions', models.IntegerField(default=0)),
                ('access_hours', models.CharField(choices=[('24/7', '24/7 Access'), ('peak', 'Peak Hours Only'), ('off-peak', 'Off-Peak Hours')], default='24/7', max_length=20)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon class or name', max_length=50)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=15)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
